import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import themeStore from '../store/themeStore';

const SECTIONS = [
  {
    title: '1. Acceptance of these terms',
    body: [
      'By creating an account or using VaadVivaad, you agree to these Terms of Service. If you don’t agree, please don’t use the platform.',
    ],
  },
  {
    title: '2. What VaadVivaad is — and isn’t',
    body: [
      'VaadVivaad simulates how a case might be argued by two AI counsel, grounded in IPC sections and precedent retrieved via semantic search.',
      'It is a research and drafting aid, built as a student project. It is not legal advice, and using it does not create any advocate-client relationship. Always verify anything it produces against primary sources and consult a licensed advocate before relying on it.',
    ],
  },
  {
    title: '3. Your account',
    body: [
      'You’re responsible for the accuracy of the information you provide and for keeping your password secure. One account per person, please.',
    ],
  },
  {
    title: '4. Acceptable use',
    body: [
      'Don’t use VaadVivaad for anything illegal, or to submit third-party confidential or privileged material you’re not authorized to share.',
      'Don’t attempt to abuse, overload, scrape, or reverse-engineer the service.',
    ],
  },
  {
    title: '5. AI-generated content',
    body: [
      'Arguments, case summaries, and precedent matches are generated by a language model. They can be incomplete, wrong, or cite things that don’t hold up — language models sometimes do that. Treat every output as a draft to verify, not a finished, citable authority.',
    ],
  },
  {
    title: '6. Your content',
    body: [
      'The case details and evidence you submit remain yours. We use them only to generate and save your debate — see the Privacy Policy for exactly how.',
    ],
  },
  {
    title: '7. Service availability',
    body: [
      'This is a student project, not a funded commercial product. It’s provided “as is,” without warranty, and may change, break, or be discontinued without notice.',
    ],
  },
  {
    title: '8. Limitation of liability',
    body: [
      'To the fullest extent permitted by law, VaadVivaad and its team aren’t liable for decisions made based on the platform’s output, or for any loss arising from its use.',
    ],
  },
  {
    title: '9. Changes to these terms',
    body: [
      'We may update these terms as the project evolves. Continued use after a change means you accept the updated terms.',
    ],
  },
];

const Terms = () => {
  const { theme } = themeStore((state) => state);
  const dark = theme === 'dark';
  const muted = dark ? 'text-gray-400' : 'text-ink-blue/60';
  const faint = dark ? 'text-gray-500' : 'text-ink-blue/50';

  return (
    <div className={`min-h-screen ${dark ? 'bg-ink text-white' : 'bg-parchment text-ink-blue'}`}>
      <section className="pt-28 md:pt-36 pb-14 px-4 md:px-10 text-center">
        <div className="max-w-3xl mx-auto">
          <motion.p
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className={`docket-label text-xs mb-4 ${faint}`}
          >
            Filed &amp; binding
          </motion.p>
          <motion.h1
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="font-display text-4xl md:text-5xl mb-4"
          >
            Terms of <span className="text-brass">Service</span>
          </motion.h1>
          <p className={`font-mono text-xs ${faint}`}>Last updated September 4, 2026</p>
        </div>
      </section>

      <section className="pb-24 md:pb-32 px-4 md:px-10">
        <div className="max-w-3xl mx-auto">
          {SECTIONS.map((s, i) => (
            <motion.div
              key={s.title}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: Math.min(i * 0.05, 0.3) }}
              className={`py-7 ${i !== 0 ? 'docket-rule' : ''}`}
            >
              <h2 className="font-display text-xl md:text-2xl mb-3">{s.title}</h2>
              {s.body.map((p, j) => (
                <p key={j} className={`text-sm leading-relaxed mb-2.5 last:mb-0 ${muted}`}>
                  {p}
                </p>
              ))}
            </motion.div>
          ))}

          <div className="docket-rule pt-8 mt-2">
            <p className={`text-sm leading-relaxed ${muted}`}>
              Questions? Reach out via the{' '}
              <Link to="/contact" className="font-medium text-brass hover:underline">
                Contact page
              </Link>{' '}
              — or read the{' '}
              <Link to="/privacy" className="font-medium text-brass hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Terms;
