"""Case brief export (Feature 08).

Rendered server-side from the structured record, not screenshotted from the
DOM: `html2canvas` produces a picture of a web page, which is useless as a
document — unsearchable, unselectable, and wrong at print sizes.

HTML is always available. PDF uses WeasyPrint when present and otherwise
falls back to headless Chrome; if neither is installed the caller gets the
HTML with an honest message rather than a broken download. DOCX is written
as a minimal OOXML package using only the standard library, since
`python-docx` is not a dependency here.
"""

from __future__ import annotations

import html
import io
import shutil
import subprocess
import tempfile
import zipfile
from pathlib import Path
from typing import TYPE_CHECKING, Tuple

from app.core.logging import get_logger
from app.services import concordance

if TYPE_CHECKING:
    from app.services.debate.machine import DebateState

log = get_logger(__name__)

DISCLAIMER = (
    "This document is generated by an automated system for research and "
    "study. It is not legal advice, it has not been reviewed by an advocate, "
    "and it must not be relied upon or filed as it stands. Verify every "
    "section number and every authority against the official text before use."
)

_CSS = """
@page { size: A4; margin: 20mm 18mm; }
body { font-family: Georgia, 'Times New Roman', serif; font-size: 10.5pt;
       line-height: 1.5; color: #1a1a1a; }
h1 { font-size: 19pt; margin: 0 0 4pt; }
h2 { font-size: 12pt; margin: 20pt 0 6pt; padding-bottom: 3pt;
     border-bottom: 1px solid #bbb; text-transform: uppercase;
     letter-spacing: .08em; }
h3 { font-size: 11pt; margin: 12pt 0 4pt; }
.meta { color: #555; font-size: 9pt; margin-bottom: 4pt; }
.turn { margin: 0 0 10pt; padding-left: 10pt; border-left: 2.5pt solid #999; }
.turn.prosecution { border-left-color: #2f6b46; }
.turn.defence { border-left-color: #96322f; }
.role { font-variant: small-caps; font-weight: bold; font-size: 9.5pt; }
.headline { font-weight: bold; }
.cite { color: #555; font-size: 9pt; }
.flag { color: #96322f; font-size: 9pt; font-style: italic; }
.ruling { background: #f5f2ea; padding: 10pt 12pt; border: 1px solid #ddd; }
table { border-collapse: collapse; width: 100%; font-size: 9.5pt; }
th, td { text-align: left; padding: 4pt 6pt; border-bottom: 1px solid #ddd;
         vertical-align: top; }
th { background: #f0ece2; }
.disclaimer { margin-top: 18pt; padding: 8pt 10pt; background: #f7f3ea;
              border: 1px solid #ccc; font-size: 8.5pt; color: #444; }
ul { margin: 3pt 0 8pt; padding-left: 16pt; }
"""


def _e(text: object) -> str:
    return html.escape(str(text or ""))


def render_html(state: "DebateState") -> str:
    case = state.case
    section_label = ""
    if state.sections:
        view = concordance.resolve(
            state.primary_section, code=state.code,
            incident_date=(case.incident_date if case else ""),
        )
        section_label = view.label()

    out: list[str] = [
        "<!doctype html><html><head><meta charset='utf-8'>",
        f"<title>Case brief — {_e(section_label or 'VaadVivaad')}</title>",
        f"<style>{_CSS}</style></head><body>",
        "<h1>Case Brief</h1>",
        f"<div class='meta'>Reference {_e(state.debate_id[:12])} · "
        f"prepared {_e(state.updated_at[:10])}"
        + (f" · {_e(section_label)}" if section_label else "") + "</div>",
    ]

    if case:
        out += ["<h2>Statement of facts</h2>", f"<p>{_e(case.summary)}</p>"]
        rows = []
        if case.incident_date:
            rows.append(("Date of incident", case.incident_date))
        if case.location:
            rows.append(("Location", case.location))
        if case.crime_type:
            rows.append(("Nature", case.crime_type.title()))
        if section_label:
            rows.append(("Provision", section_label))
        if rows:
            out.append("<table>" + "".join(
                f"<tr><th>{_e(k)}</th><td>{_e(v)}</td></tr>" for k, v in rows
            ) + "</table>")
        if case.parties:
            out.append("<h3>Parties</h3><ul>" + "".join(
                f"<li>{_e(p.role)}{': ' + _e(p.name) if p.name else ''}</li>"
                for p in case.parties) + "</ul>")
        if case.evidence:
            out.append("<h3>Evidence on the record</h3><ul>" + "".join(
                f"<li>{_e(i.description)}"
                f"{' <span class=cite>(in possession)</span>' if i.in_possession else ''}</li>"
                for i in case.evidence) + "</ul>")

    if state.statute:
        out += ["<h2>The provision</h2>",
                f"<p>{_e(state.statute.definition)}</p>"]
        if state.statute.elements:
            out.append("<h3>Elements</h3><ul>" + "".join(
                f"<li><b>{_e(el.element)}</b> — {_e(el.description)}</li>"
                for el in state.statute.elements) + "</ul>")
        if not state.statute_verified:
            out.append("<p class='flag'>The statutory summary above is "
                       "machine-generated and unverified. Check it against the "
                       "bare Act.</p>")

    out.append("<h2>Authorities</h2>")
    if state.precedents:
        out.append("<ul>" + "".join(
            f"<li><b>{_e(p.case_name)}</b>"
            f"{' — ' + _e(p.court) if p.court else ''}"
            f"{' (' + _e(p.date[:4]) + ')' if p.date else ''}"
            f"{'<br><span class=cite>' + _e(p.holding) + '</span>' if p.holding else ''}"
            f"{'<br><span class=cite>' + _e(p.source_url) + '</span>' if p.source_url else ''}"
            "</li>" for p in state.precedents) + "</ul>")
    else:
        out.append("<p class='flag'>No verified precedent was located for this "
                   "matter. The arguments below rest on the statutory elements "
                   "and the record alone.</p>")

    out.append("<h2>The hearing</h2>")
    for turn in state.turns:
        content = turn.content
        cites = ", ".join(content.relies_on)
        out.append(
            f"<div class='turn {turn.side.value}'>"
            f"<div class='role'>{_e(turn.side.value)} · round {turn.round} · "
            f"{_e(turn.phase.value)}</div>"
            f"<div class='headline'>{_e(content.headline)}</div>"
            f"<div>{_e(content.argument)}</div>"
            + (f"<div class='cite'>Relies on: {_e(cites)}</div>" if cites else "")
            + ("<div class='flag'>Unsupported citations were removed from this "
               "submission.</div>" if turn.unsupported_citations else "")
            + "</div>"
        )
    if not state.turns:
        out.append("<p>No argument was heard.</p>")

    if state.ruling:
        ruling = state.ruling
        out += [
            "<h2>Order</h2><div class='ruling'>",
            f"<p><b>Decisive issue.</b> {_e(ruling.decisive_issue)}</p>",
            f"<p><b>Disposition.</b> {_e(ruling.disposition)}</p>",
            f"<p class='cite'>Favoured: {_e(ruling.favoured_side.value)} · "
            f"confidence {ruling.confidence:.2f}</p>",
        ]
        if ruling.would_change_if:
            out.append("<p><b>What would change this:</b></p><ul>" + "".join(
                f"<li>{_e(x)}</li>" for x in ruling.would_change_if) + "</ul>")
        out.append("</div>")

    gaps = (state.gaps or {}).get("gaps") or []
    if gaps:
        out.append("<h2>Evidence gaps</h2><table>"
                   "<tr><th>Element</th><th>Missing</th><th>How to obtain</th>"
                   "<th>Severity</th></tr>")
        for gap in gaps:
            out.append(
                f"<tr><td>{_e(gap.get('element'))}</td>"
                f"<td>{_e(gap.get('missing'))}</td>"
                f"<td>{_e(gap.get('obtain_how'))}"
                f"{'<br><span class=cite>' + _e(gap.get('provision')) + '</span>' if gap.get('provision') else ''}</td>"
                f"<td>{_e(gap.get('severity'))}</td></tr>")
        out.append("</table>")

    out.append(f"<div class='disclaimer'>{_e(DISCLAIMER)}</div>")
    out.append("</body></html>")
    return "".join(out)


def _html_to_pdf(markup: str) -> bytes | None:
    try:
        from weasyprint import HTML  # type: ignore

        return HTML(string=markup).write_pdf()
    except ImportError:
        pass
    except Exception as exc:  # pragma: no cover - renderer specifics
        log.warning("export.weasyprint_failed", extra={"error": str(exc)[:160]})

    chrome = next((shutil.which(name) for name in
                   ("google-chrome", "chromium", "chromium-browser")
                   if shutil.which(name)), None)
    if not chrome:
        return None
    with tempfile.TemporaryDirectory() as tmp:
        source = Path(tmp) / "brief.html"
        target = Path(tmp) / "brief.pdf"
        source.write_text(markup, encoding="utf-8")
        try:
            subprocess.run(
                [chrome, "--headless", "--disable-gpu", "--no-sandbox",
                 "--no-pdf-header-footer", f"--print-to-pdf={target}",
                 source.as_uri()],
                check=True, capture_output=True, timeout=60,
            )
            return target.read_bytes() if target.exists() else None
        except (subprocess.SubprocessError, OSError) as exc:
            log.warning("export.chrome_failed", extra={"error": str(exc)[:160]})
            return None


def _html_to_docx(markup: str, state: "DebateState") -> bytes:
    """Minimal but valid OOXML, built with the standard library.

    Word documents are a zip of XML parts; for a linear brief this is a few
    dozen lines and avoids taking a dependency that cannot be installed here.
    """
    def para(text: str, *, bold: bool = False, size: int = 22,
             space_after: int = 120) -> str:
        runs = (f'<w:rPr>{"<w:b/>" if bold else ""}'
                f'<w:sz w:val="{size}"/></w:rPr>')
        return (f'<w:p><w:pPr><w:spacing w:after="{space_after}"/></w:pPr>'
                f'<w:r>{runs}<w:t xml:space="preserve">{_e(text)}</w:t></w:r></w:p>')

    body: list[str] = [para("Case Brief", bold=True, size=36)]
    if state.case:
        body.append(para("Statement of facts", bold=True, size=26))
        body.append(para(state.case.summary))
    body.append(para("The hearing", bold=True, size=26))
    for turn in state.turns:
        body.append(para(f"{turn.side.value.title()} — round {turn.round} "
                         f"({turn.phase.value})", bold=True, size=22))
        body.append(para(turn.content.headline, bold=True))
        body.append(para(turn.content.argument))
    if state.ruling:
        body.append(para("Order", bold=True, size=26))
        body.append(para(f"Decisive issue: {state.ruling.decisive_issue}"))
        body.append(para(f"Disposition: {state.ruling.disposition}"))
        body.append(para(f"Confidence: {state.ruling.confidence:.2f}"))
    body.append(para(DISCLAIMER, size=18))

    document = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        f'<w:body>{"".join(body)}</w:body></w:document>'
    )
    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        '</Types>'
    )
    rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
        '</Relationships>'
    )
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", content_types)
        archive.writestr("_rels/.rels", rels)
        archive.writestr("word/document.xml", document)
    return buffer.getvalue()


async def render_brief(state: "DebateState", fmt: str = "pdf") -> Tuple[bytes, str, str]:
    """Returns (content, media_type, filename)."""
    markup = render_html(state)
    stem = f"vaadvivaad-brief-{state.debate_id[:8]}"

    if fmt == "html":
        return markup.encode("utf-8"), "text/html; charset=utf-8", f"{stem}.html"

    if fmt == "docx":
        return (_html_to_docx(markup, state),
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                f"{stem}.docx")

    pdf = _html_to_pdf(markup)
    if pdf is None:
        log.warning("export.pdf_unavailable")
        notice = markup.replace(
            "<h1>Case Brief</h1>",
            "<p class='flag'>PDF rendering is not available on this server; "
            "this is the HTML version. Print to PDF from your browser.</p>"
            "<h1>Case Brief</h1>")
        return notice.encode("utf-8"), "text/html; charset=utf-8", f"{stem}.html"
    return pdf, "application/pdf", f"{stem}.pdf"
